import "./globals.css";
import Footer from "./Footer/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const assetBasepath = process.env.NEXT_PUBLIC_BASEPATH + "/";
// Metadata also to be updated in manifest and xml file
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="mask-icon"
          href={assetBasepath + "favicon/safari-pinned-tab.svg"}
          color="#5bbad5"
        />
        {/* primary color */}
        <meta name="msapplication-TileColor" content="#00916e" />
        <meta
          name="msapplication-config"
          content={assetBasepath + "favicon/browserconfig.xml"}
        />
      </head>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
